export const SHOW_PAGE_LOADING = 'SHOW_PAGE_LOADING';
export const HIDE_PAGE_LOADING = 'HIDE_PAGE_LOADING';

export const GET_CURRENT_USER = 'GET_CURRENT_USER';

export const CLEAR_APP_VERSION = 'CLEAR_APP_VERSION';


